<?php

// autoload-classmap.php @generated by Strauss

$strauss_src = dirname(__FILE__);

return array(
   'WooCommerceMinMaxQuantities\ByteKit\Admin\Settings' => $strauss_src . '/byteever/bytekit-settings/src/Admin/Settings.php',
   'WooCommerceMinMaxQuantities\ByteKit\Scripts' => $strauss_src . '/byteever/bytekit-plugin/src/Scripts.php',
   'WooCommerceMinMaxQuantities\ByteKit\Traits\HasPlugin' => $strauss_src . '/byteever/bytekit-plugin/src/Traits/HasPlugin.php',
   'WooCommerceMinMaxQuantities\ByteKit\Services' => $strauss_src . '/byteever/bytekit-plugin/src/Services.php',
   'WooCommerceMinMaxQuantities\ByteKit\Plugin' => $strauss_src . '/byteever/bytekit-plugin/src/Plugin.php',
   'WooCommerceMinMaxQuantities\ByteKit\Admin\Flash' => $strauss_src . '/byteever/bytekit-plugin/src/Admin/Flash.php',
   'WooCommerceMinMaxQuantities\ByteKit\Admin\Notices' => $strauss_src . '/byteever/bytekit-plugin/src/Admin/Notices.php',
   'WooCommerceMinMaxQuantities\ByteKit\Interfaces\Pluginable' => $strauss_src . '/byteever/bytekit-plugin/src/Interfaces/Pluginable.php',
   'WooCommerceMinMaxQuantities\ByteKit\Interfaces\Scriptable' => $strauss_src . '/byteever/bytekit-plugin/src/Interfaces/Scriptable.php',
);